name: Every Logger

on:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  logging_event:
    runs-on: 'ubuntu-22.04'
    steps:
      - name: Log Event
        run: |
          echo ${{toJSON(github.event)}}
      - name: Log Commits
        run: |
          echo ${{toJSON(github.event.commits)}}
          
  logging_pr:
    runs-on: 'ubuntu-22.04'
    steps:
    - name : Log PR
      run: |
        echo ${{toJSON(github.event.pull_request)}}
    - name : Log PR title
      run: |
        echo ${{ github.event.pull_request.title }}
    - name: Log PR body
      run: |
        echo ${{ github.event.pull_request.body }}
  
  logging_tags:
    runs-on: 'ubuntu-22.04'
    steps:
    - name: Log Tags
      run: |
        TAG=${GITHUB_REF#refs/tags/};
        echo TAG
