name: Event Logger

on:
  push:
    branches:
      - 'main'
jobs:
  logging_action:
    runs-on: 'ubuntu-22.04'
    steps:
      - name: Log Event
        run: |
          echo "${{toJSON(github.event)}}"
      - name: Log
        if: github.event_name == 'release'
        run: |
          # Remove 'refs/tags/' to get the actual tag from the release.
          TAG=${GITHUB_REF#refs/tags/};
          VERSION=$(scripts/get_version.py current)
          if [ "$TAG" != "$VERSION" ]; then
              echo "Bad tag or version. Tag $TAG does not match $VERSION";
              exit 1;
          fi
